### ISSUE TITLE
suggestions

### ISSUE THREAD

**Issue by pengzhangzhi** [deepmodeling/AI4Science101#16]
wonderful repo! I checked your doc, which seems like just putting related contents together. As a beginner in scientific domain, I really can't understand them just by reading them. It is better to organize your tutorial by project. For example, I am working on protein structure prediction and have no background on chemistry and biology. A tutorial I may find very informative would be the introduction of related knowledge that can help me complete my project. To be honest, your current tutorial is like Chinese textbook. Don't get wrong, I am trying to help you guys!

**Comment by likefallwind** [comment]
Thanks for your advice.
Maybe Molecular Dynamics part is the tutorial you want?

This is only the first edition, so we try to draw a roadmap of AI4Science. Later we will give some project, but we need time hahaha.

**Comment by pengzhangzhi** [comment]
Thanks. You guys did a great job! I am looking forward to the subsequent editions~ By the way, the Molecular Dynamics part seems not what I want. I would prefer stuff like biology, protein structure, etc. If you have related contents, please let me know~

**Comment by yuanqidu** [comment]
We would suggest you to take a look at the knowledge base which collects common terminologies in each area, if you are looking for further and more thorough study, we would suggest to go over the learning material, mostly books for scientific fields right now, we will also keep it updated, feel free to let us know as well if you find any material that helps including but not limited to tutorials, books, (online) courses/lectures, review papers that may benefit many others!

**Comment by pengzhangzhi** [comment]
I personally maintain an [awesome list in computational biology](https://github.com/pengzhangzhi/Awesome-Computational-Structural-Biology), which collects many great tutorials and courses in the field of biology, ML, DL etc.

**Comment by yuanqidu** [comment]
Thanks for sharing! It looks great! We also welcome and appreciate contributions!
